# =========================
# ADMIN (3001)
# =========================
server {
    server_name admin.infradaily.dev;

    location / {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    client_max_body_size 50M;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/admin.infradaily.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.infradaily.dev/privkey.pem;
}

server {
    listen 80;
    server_name admin.infradaily.dev;
    return 301 https://$host$request_uri;
}


# =========================
# API (5001)
# =========================
server {
    server_name api.infradaily.dev;

    location / {
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    client_max_body_size 50M;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/admin.infradaily.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.infradaily.dev/privkey.pem;
}

server {
    listen 80;
    server_name api.infradaily.dev;
    return 301 https://$host$request_uri;
}


# =========================
# APP (3000)
# =========================
server {
    server_name app.infradaily.dev;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    client_max_body_size 50M;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/admin.infradaily.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.infradaily.dev/privkey.pem;
}

server {
    listen 80;
    server_name app.infradaily.dev;
    return 301 https://$host$request_uri;
}